### ISSUE TITLE
Simple Origin Relay 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#1]
- [ ] Accept HTTP PUT & GET 
- [ ] Deployed on AWS 
- [ ] work with short and long names 
- [ ] data backed with S3 using short names 
- [ ] support for QuicR pub/sub
