### ISSUE TITLE
Simple Relay 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#13]
- [ ] simple relay that runs QuicR 
- [ ] running in docker image on static IP with no MDNS 
- [ ] deploy and RPi 
- [ ] discover with MDNS on local network 
- [ ] easy way to deploy on new RPi 
- [ ] deploy on anycast IP in cloud
