### ISSUE TITLE
Dump Tool 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#2]
- [ ] Connect to origin relay and get files over HTTP 
- [ ] Spider team or org and get all files 
- [ ] Save files to local disk using long names 
- [ ] Work with QuicR protocol to any relay
