### ISSUE TITLE
UnDump Tool

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#3]
More or less opposite of Dump Tool. Take set of files on local disk with long names and publish. 

- [ ] upload single file with HTTP 
- [ ] scan directory of files and upload all 
- [ ] publish with QuicR instead of HTTP
