### ISSUE TITLE
Secure Processor 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#6]
Written in Rust.

- [ ] Setup API
- [ ] encrypt / decrypt with simply adding "enc:" before message 
- [ ] link incoming / outgoing messages from NetProc to UIProc 
- [ ] generate and publish KP
- [ ] process MLS welcome 
- [ ] process MLS commit 
- [ ] do real encryption
