### ISSUE TITLE
Network Proc for OSX 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#7]
Only works with short names. Develop initially for OSX then port to others. 

- [ ] Send  with HTTP PUT to origin relay 
- [ ] Receive with HTTP GET to origin relay (not real subscribe, only get single file if exits)
- [ ] pub/sub with QuicR 
- [ ] port to embedded system
