### ISSUE TITLE
Admin Tool 

### ISSUE THREAD

**Issue by fluffy** [Quicr/qmsg#8]
OSX CLI Tool to create team, channels, and add and remove users 

Assumes that there is only one admin user for an org.  Does all it interactions with HTTP PUT/GET to Origin relay to start with. 

- [ ] Create a team and add admin user to it 
- [ ] add new users to team 
- [ ] create a channel 
- [ ] list all teams in org 
- [ ] list all devices in team 
- [ ] list all channels in team
- [ ] change name of channel
- [ ] change name of team 
- [ ] use QuicR to relay for PUB/SUB instead of HTTP
